security:
    # Remplacez "encoders" par "password_hashers"
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            # Assurez-vous que cette configuration est correcte  
            entity:
                class: App\Entity\User  
                property: email

    firewalls:
        main:
            # Utilisez "stateless: true" si vous utilisez une API ou laissez de côté si vous avez besoin de sessions  
            stateless: false  
            form_login:
                # Chemins de connexion  
                login_path: app_login  
                check_path: app_login 
                default_target_path: /  
            logout:
                path: app_logout  
                target: app_login  # Redirection après déconnexion

    access_control:
        - { path: ^/protected, roles: ROLE_USER }
        # - { path: ^/login, roles: ROLE_USER }  # Autoriser l'accès à la page de connexion